### ISSUE TITLE
Als examen coördinator   Wil ik een lokaal kunnen toevoegen aan het programma Zodat ik kan selecteren in welk lokaal een examen plaats kan vinden

### ISSUE THREAD

**Issue by Devilskey** [TamoAgzt/Smort-Examen-Tool-API#14]
**Front-end:** 

- [x] Link de knop met de form en zorg dat als er op + wordt geklikt de form wordt geopend 
- [x] Maak een form waar mee een lokaal toegevoegd kan worden 
- [x] Link de knop met de form en zorg dat als er op + wordt geklikt de form wordt geopend 

**Intergratie**

- [x] zorg dat de api call wordt opgeroepen zodat het nieuwe lokaal word toegevoegd

**Comment by TamoAgzt** [comment]
Picking up task
Getting to work on branch [feature](https://github.com/TamoAgzt/Smort-Examen-Tool-Webapp/tree/feature/Add_ClassRoom)

**Comment by Devilskey** [comment]
Done
