### ISSUE TITLE
Als examen coördinator   Wil ik een klas kunnen aanmaken Zodat gebruikers ook echt hun klas kunnen selecteren wanneer ze zich aanmelden

### ISSUE THREAD

**Issue by Devilskey** [TamoAgzt/Smort-Examen-Tool-API#16]

**Comment by Devilskey** [comment]
**Front-end:** 

- [ ] Maak een + Button naast het Klas selectie 
- [ ] Maak een form waar mee een Klas toegevoegd kan worden 
- [ ] Link de knop met de form en zorg dat als er op + wordt geklikt de form wordt geopend 


**Intergratie:** 

- [ ] Zorg dat de api call wordt opgeroepen zodat het nieuwe Klas wordt toegevoegd

**Comment by TamoAgzt** [comment]
Wordt gedaan in branch [feature/Add_ClassRoom](https://github.com/TamoAgzt/Smort-Examen-Tool-Webapp/tree/feature/Add_ClassRoom)

**Comment by Devilskey** [comment]
Done
